# Generated by Django 5.1.6 on 2026-08-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutlookIntakeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject_contains', models.CharField(blank=True, max_length=300)),
                ('sender_contains', models.CharField(blank=True, max_length=300)),
                ('set_urgency', models.CharField(default='normal', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcuraFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procura_field', models.CharField(max_length=200)),
                ('carelink_field', models.CharField(max_length=200)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('procura_field', 'carelink_field')},
            },
        ),
    ]
