# Generated by Django 5.1.6 on 2026-08-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_platformsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('change_requested', 'Change Requested'), ('approved_pending_change', 'Approved, Pending Change')], default='scheduled', max_length=30),
        ),
    ]
