# Generated by Django 5.1.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_alter_shift_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='audience',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
